name: AccessAbility
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  easy_localization: ^3.0.0
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  audioplayers: ^6.1.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_maps_flutter: ^2.10.0
  cloud_firestore: ^6.0.0
  provider: ^6.1.2
  intl: ^0.20.2
  location: ^8.0.0
  url_launcher: ^6.1.11
  tutorial_coach_mark: ^1.2.12
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  logging: ^1.3.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_dotenv: ^5.2.1
  firebase_messaging: ^16.0.0
  emoji_picker_flutter: ^4.3.0
  flutter_local_notifications: ^19.4.0
  flutter_slidable: ^4.0.0
  local_auth: ^2.3.0
  firebase_storage: ^13.0.0
  image_picker: ^1.1.2
  workmanager: ^0.9.0+2
  flutter_background_service: ^5.1.0
  rxdart: ^0.28.0
  device_info_plus: ^11.3.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  google_fonts: ^6.2.1
  flutter_polyline_points: 2.1.0
  font_awesome_flutter: ^10.4.0

  #ForVoiceCommandDependencies
  http: ^1.2.1
  tflite_flutter: ^0.11.0
  permission_handler: ^12.0.1
  # Removed tflite_flutter_helper to fix version conflict

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/authentication/authenticationImage.png
    - assets/animation/
    - assets/images/others/
    - assets/images/onboarding/
    - assets/images/settings/
    - assets/images/others/biometricslogo.png
    - assets/images/others/accessabilitylogo.png
    - assets/images/others/hotel.png
    - assets/images/others/grocery.png
    - assets/images/others/restaurant.png
    - assets/images/others/bus-school.png
    - assets/images/others/shopping-mall.png
    - assets/images/others/default_profile.png
    - assets/images/others/marker_shape.png
    - assets/images/others/marker_shape_selected.png
    - assets/images/others/group_chat_icon.jpg
    - assets/map_styles/dark_mode.json
    - assets/images/settings/biometric_login.png
    - assets/model/best_dory_model.tflite
    - assets/model/dory_model_final.tflite
    - .env

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/helvetica/HelveticaNeueUltraLight.otf
          weight: 100
        - asset: assets/fonts/helvetica/HelveticaNeueUltraLightItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/helvetica/HelveticaNeueThin.otf
          weight: 200
        - asset: assets/fonts/helvetica/HelveticaNeueThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/helvetica/HelveticaNeueLight.otf
          weight: 300
        - asset: assets/fonts/helvetica/HelveticaNeueLightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/helvetica/HelveticaNeueRoman.otf
          weight: 400
        - asset: assets/fonts/helvetica/HelveticaNeueItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/helvetica/HelveticaNeueMedium.otf
          weight: 500
        - asset: assets/fonts/helvetica/HelveticaNeueMediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/helvetica/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/fonts/helvetica/HelveticaNeueBoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/helvetica/HelveticaNeueHeavy.otf
          weight: 800
        - asset: assets/fonts/helvetica/HelveticaNeueHeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/helvetica/HelveticaNeueBlack.otf
          weight: 900
        - asset: assets/fonts/helvetica/HelveticaNeueBlackItalic.otf
          weight: 900
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
