name: AI Code Review (Free Hugging Face)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.repository }}

      - name: Get PR diff
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }} > changes.diff

      - name: Run AI Review with HuggingFace
        run: |
          pip install requests
          DIFF=$(cat changes.diff | head -c 4000)
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"inputs\":\"Review this code diff for bugs, readability, and improvements:\\n$DIFF\"}" \
            https://api-inference.huggingface.co/models/bigcode/starcoder2-3b)
          echo "$RESPONSE" > review.txt

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: review.txt
