name: Notify Messenger on Push

on:
  push:
    branches: [ main ] # or any branch you want

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Facebook Messenger
        run: |
          curl -X POST "https://graph.facebook.com/v19.0/me/messages?access_token=${{ secrets.PAGE_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "recipient": { "id": "'"${{ secrets.PSID }}"'" },
            "message": { "text": "🆕 New commit pushed to ${{ github.repository }} by ${{ github.actor }}!" }
          }'
