name: Notify via Messenger on Push

on:
  push:
    branches:
      - main  # or whatever branch you care about

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Messenger message to all PSIDs
        run: |
          # Prepare data
          PSID_LIST="${{ secrets.PSID_LIST }}"
          ACCESS_TOKEN="${{ secrets.PAGE_ACCESS_TOKEN }}"
          IFS=',' read -ra PSIDS <<< "$PSID_LIST"

          REPO_NAME="${GITHUB_REPOSITORY}"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"

          # Send to each PSID
          for PSID in "${PSIDS[@]}"; do
            echo "📤 Sending commit info to $PSID..."

            curl -X POST "https://graph.facebook.com/v19.0/me/messages?access_token=$ACCESS_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "recipient": { "id": "'"$PSID"'" },
                "message": {
                  "text": "📦 Repo: '"$REPO_NAME"'\n👤 '"$COMMIT_AUTHOR"' pushed:\n💬 '"$COMMIT_MESSAGE"'\n🔗 '"$COMMIT_URL"'"
                }
              }'
          done
