name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Setup Node.js (for semantic-release)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # ✅ Install dependencies (semantic-release + plugins included)
      - name: Install dependencies
        run: npm install

      # ✅ Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ~/.flutter-sdk
          key: flutter-${{ runner.os }}-3.32.7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          cache: true

      # ✅ Cache Flutter pub packages
      - name: Cache Flutter pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            frontend/.dart_tool
          key: pub-${{ runner.os }}-${{ hashFiles('frontend/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      # ✅ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('frontend/android/build.gradle','frontend/android/app/build.gradle') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # ✅ Install Flutter dependencies
      - name: Get Flutter packages
        working-directory: frontend
        run: flutter pub get

      # ✅ Build release APK
      - name: Build APK
        working-directory: frontend
        run: flutter build apk --release

      # ✅ Upload artifact for manual download
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: frontend/build/app/outputs/flutter-apk/app-release.apk

      # ✅ Semantic Release (GitHub release + changelog)
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
